// Builds the synthetic package design-sync treats as the design system.
// Respondly is a Next.js app, not a published component library, so there is
// no dist/ to point the converter at. This script produces one:
//   .design-sync/pkg/index.ts    barrel over src/components/ui/*.tsx
//   .design-sync/pkg/dist/**     real .d.ts tree (tsc --emitDeclarationOnly)
//   .design-sync/pkg/styles.css  compiled Tailwind (see build-css.mjs)
// Run build-css.mjs first, then this, then package-build.mjs.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, rmSync, writeFileSync, copyFileSync } from 'node:fs';

const UI = 'src/components/ui';
const PKG = '.design-sync/pkg';
mkdirSync(PKG, { recursive: true });

const mods = readdirSync(UI)
  .filter((f) => f.endsWith('.tsx') && !/\.(test|stories)\./.test(f))
  .map((f) => f.replace(/\.tsx$/, ''))
  .sort();

const header = '// generated by .design-sync/build-pkg.mjs — do not edit\n';
writeFileSync(PKG + '/index.ts', header + mods.map((m) => `export * from "../../${UI}/${m}";`).join('\n') + '\n');
writeFileSync(
  PKG + '/package.json',
  JSON.stringify({ name: 'respondly', version: '0.1.0', private: true, types: 'dist/index.d.ts' }, null, 2) + '\n',
);
writeFileSync(
  PKG + '/tsconfig.json',
  JSON.stringify(
    {
      extends: '../../tsconfig.json',
      compilerOptions: {
        noEmit: false,
        declaration: true,
        emitDeclarationOnly: true,
        incremental: false,
        outDir: 'dist',
        rootDir: '../..',
        paths: { '@/*': ['../../src/*'], '@emails/*': ['../../emails/*'] },
      },
      include: ['index.ts'],
      exclude: ['dist'],
    },
    null,
    2,
  ) + '\n',
);

rmSync(PKG + '/dist', { recursive: true, force: true });
execFileSync('npx', ['tsc', '-p', PKG + '/tsconfig.json'], { stdio: 'inherit' });

// tsc mirrors rootDir, so the barrel lands at dist/.design-sync/pkg/index.d.ts.
// The converter globs `<dirname(types)>/**/*.d.ts`, so the barrel has to sit at
// the dist root with its specifiers rewritten to match.
rmSync(PKG + '/dist/.design-sync', { recursive: true, force: true });
writeFileSync(PKG + '/dist/index.d.ts', header + mods.map((m) => `export * from "./${UI}/${m}";`).join('\n') + '\n');

copyFileSync('.design-sync/build/tailwind.css', PKG + '/styles.css');
console.error(`pkg: ${mods.length} ui modules → ${PKG}/dist`);
